### ISSUE TITLE
ImportError: cannot import name 'processors' from 'sqlalchemy'

### ISSUE THREAD

**Issue by aa89113** [gordthompson/sqlalchemy-sybase#8]
This package requires sqlachemy <2.0...
I am getting this error with python 3.9.13 and sqlachemy v2.0:

``ImportError: cannot import name 'processors' from 'sqlalchemy'``

SQLAlchemy==2.0.0
pyodbc==4.0.35
sqlalchemy-sybase==1.0.6

Works fine with sqlachemy < 2.0

**Comment by gordthompson** [comment]
Thanks for reporting. I'll look into it.
